### ISSUE TITLE
withErrorBoundary: ref type collapses to Component<unknown, any, any> since 6.1.0

### ISSUE THREAD

**Issue by Alberto-BaseNet** [bvaughn/react-error-boundary#248]
### Summary

Since 6.1.0, passing a ref to a component wrapped by `withErrorBoundary` does not type-check unless the ref happens to be a class instance.

### Repro

```tsx
import { useImperativeHandle, type Ref } from "react";
import { withErrorBoundary } from "react-error-boundary";

type Handle = { focus: () => void };

function Editor({ ref }: { ref?: Ref<Handle> }) {
  useImperativeHandle(ref, () => ({ focus() {} }));
  return null;
}

const Wrapped = withErrorBoundary(Editor, { fallback: null });

// error TS2322
<Wrapped ref={useRef<Handle>(null)} />;
```

```
Type 'RefObject<Handle | null>' is not assignable to type
'Ref<Component<unknown, any, any>> | undefined'.
```

### Cause

```ts
export function withErrorBoundary<
  Type extends ComponentClass<unknown>,
  Props extends object,
>(Component: ComponentType<Props>, errorBoundaryProps: ErrorBoundaryProps)
```

`Type` is not mentioned by any parameter, so it can never be inferred and always falls back to its constraint. `InstanceType<ComponentClass<unknown>>` is `Component<unknown, any, any>`, so every wrapper is typed as taking a ref to that regardless of what the wrapped component's ref actually is.

6.0.0 inferred from the component and derived both sides from it:

```ts
export declare function withErrorBoundary<T extends ComponentType<any>>(
  component: T, errorBoundaryProps: ErrorBoundaryProps
): ForwardRefExoticComponent<PropsWithoutRef<ComponentProps<T>> & RefAttributes<ComponentRef<T>>>;
```

Introduced in #211. It went unnoticed because the ref test in `withErrorBoundary.test.tsx` passes a class component, and a class instance does structurally satisfy `Component<unknown, any, any>`. Function components that declare a `ref` prop — the React 19 form — are the ones that break.

Runtime is unaffected; the HOC already forwards the ref correctly. It is only the declared type.

### Context

Found while upgrading a React 19 CRM frontend from 6.0.0; it breaks 9 call sites, so we are pinned to 6.0.0. Still present in 6.1.4.

Happy to send the PR — it restores inference over the component and adds a function-component ref test that fails to compile without it. Opening this first per CONTRIBUTING.md.

**Comment by bvaughn** [comment]
Published in version 6.1.5
