### PR TITLE
Infer the wrapped component's ref type in withErrorBoundary

### LINKED ISSUE #248: withErrorBoundary: ref type collapses to Component<unknown, any, any> since 6.1.0
### Summary

Since 6.1.0, passing a ref to a component wrapped by `withErrorBoundary` does not type-check unless the ref happens to be a class instance.

### Repro

```tsx
import { useImperativeHandle, type Ref } from "react";
import { withErrorBoundary } from "react-error-boundary";

type Handle = { focus: () => void };

function Editor({ ref }: { ref?: Ref<Handle> }) {
  useImperativeHandle(ref, () => ({ focus() {} }));
  return null;
}

const Wrapped = withErrorBoundary(Editor, { fallback: null });

// error TS2322
<Wrapped ref={useRef<Handle>(null)} />;
```

```
Type 'RefObject<Handle | null>' is not assignable to type
'Ref<Component<unknown, any, any>> | undefined'.
```

### Cause

```ts
export function withErrorBoundary<
  Type extends ComponentClass<unknown>,
  Props extends object,
>(Component: ComponentType<Props>, errorBoundaryProps: ErrorBoundaryProps)
```

`Type` is not mentioned by any parameter, so it can never be inferred and always falls back to its constraint. `InstanceType<ComponentClass<unknown>>` is `Component<unknown, any, any>`, so every wrapper is typed as taking a ref to that regardless of what the wrapped component's ref actually is.

6.0.0 inferred from the component and derived both sides from it:

```ts
export declare function withErrorBoundary<T extends ComponentType<any>>(
  component: T, errorBoundaryProps: ErrorBoundaryProps
): ForwardRefExoticComponent<PropsWithoutRef<ComponentProps<T>> & RefAttributes<ComponentRef<T>>>;
```

Introduced in #211. It went unnoticed because the ref test in `withErrorBoundary.test.tsx` passes a class component, and a class instance does structurally satisfy `Component<unknown, any, any>`. Function components that declare a `ref` prop — the React 19 form — are the ones that break.

Runtime is unaffected; the HOC already forwards the ref correctly. It is only the declared type.

### Context

Found while upgrading a React 19 CRM frontend from 6.0.0; it breaks 9 call sites, so we are pinned to 6.0.0. Still present in 6.1.4.

Happy to send the PR — it restores inference over the component and adds a function-component ref test that fails to compile without it. Opening this first per CONTRIBUTING.md.

### PR DESCRIPTION
**Pull request by Alberto-BaseNet**
Fixes #248.

`withErrorBoundary` was parameterized over `Type extends ComponentClass<unknown>`, but no parameter mentions `Type`, so it can never be inferred and always falls back to its constraint. Every wrapper came out typed as taking `Ref<Component<unknown, any, any>>`, so passing the ref the wrapped component actually takes fails to compile.

This parameterizes over the component instead, so `Type` is inferred from the argument, and reads both sides off it with `ComponentProps` / `ComponentRef` — matching what the runtime already forwards, and what 6.0.0 declared.

The existing ref test passes a class component, whose instance structurally satisfies `Component<unknown, any, any>`, which is why this survived #211. The added test passes a function component declaring a `ref` prop — the React 19 form — and does not compile without the change.

The constraint needs `any` because React's own `ComponentProps` and `ComponentRef` are constrained by `JSXElementConstructor<any>`; there is a comment and a narrow eslint exception on that line.

Motivation: we hit this upgrading a React 19 CRM frontend off 6.0.0, where it breaks 9 call sites and keeps us pinned.

Co-authored-by: Claude Opus 5 <noreply@anthropic.com>

### CODE REVIEW

**Review by bvaughn — APPROVED** [review]
Thanks for the PR, Alberto 👍🏼

**Comment by bvaughn** [comment]
Published in react-error-boundary@6.1.5
